<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Resources\deadlock_tweaker.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\deadlock_tweaker.ico" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Spectre.Console" Version="0.50.0" />
	</ItemGroup>

</Project>
